backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "image", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "slides"
    label: "activities"
    folder: "content/slides"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Featured Image", widget: "image" }
  - name: "about"
    label: "about"
    folder: "content/about"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "vision", label: "Vision", widget: "text" }
      - { name: "mission", label: "Mission", widget: "text" }
      - { name: "about", label: "About", widget: "markdown" }
  - name: "team"
    label: "team"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
       - { name: "image", label: "Featured Image", widget: "image" }
       - { name: "role", label: "Role", widget: "string" }
  - name: "project"
    label: "Project"
    folder: "content/project"
    create: true
    slug: "{{slug}}"
    fields:
       - { name: "title", label: "Project title", widget: "string" }
       - { name: "description", label: "Description", widget: "text" }
  - name: "activities"
    label: "activities"
    folder: "content/activities"
    create: true
    slug: "{{slug}}"
    fields:
       - { name: "title", label: "Activity title", widget: "string" }
       - { name: "description", label: "Description", widget: "text" }
  - name: "publications"
    label: "publications"
    folder: "content/publications"
    create: true
    slug: "{{slug}}"
    fields:
       - { name: "title", label: "Activity title", widget: "string" }
       - { name: "description", label: "Description", widget: "text" }

      
